spring:
  datasource:
    url: jdbc:h2:file:C:\Users\Alien17\data
  driverClassName: org.h2.Driver
  username: sa
  password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
   console:
    enabled: true

  server:
    port: 15000